services:
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            TZ: America/Bogota
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - default
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - APP_ENV=$APP_ENV
        volumes:
            - ./courier/:/var/www/symfony/
        networks:
            - default
        depends_on:
            - db
        entrypoint: >
            sh -c "composer install && cron && php-fpm"
    nginx:
        image: nginx
        volumes:
            - ./courier/:/var/www/symfony/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        networks:
            - default
        depends_on:
            - php
networks:
    default:
        name: courier