services:
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            TZ: America/Bogota
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - courier
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - APP_ENV=$APP_ENV
        volumes:
            - ./courier/:/var/www/symfony/
            - ./courier/public/files/:/var/www/symfony/public/files/
            - ./courier/public/error/:/var/www/symfony/public/error/
            - ./courier/public/planos/:/var/www/symfony/public/planos/
        networks:
            - courier
        depends_on:
            - db
        entrypoint: >
            sh -c "composer install && php-fpm"

    cron:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
        args:
          - APP_ENV=$APP_ENV
      volumes:
        - ./courier/:/var/www/symfony/
        - ./courier/public/files/:/var/www/symfony/public/files/
        - ./courier/public/error/:/var/www/symfony/public/error/
        - ./courier/public/planos/:/var/www/symfony/public/planos/
        - ./crontab:/etc/cron.d/check-cron
      networks:
        - courier
      depends_on:
        - db
      entrypoint: >
        sh -c "composer install && cron -f"

    nginx:
        image: nginx
        volumes:
            - ./courier/:/var/www/symfony/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        networks:
            - courier
        depends_on:
            - php
networks:
    courier:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.0/16
                  gateway: 172.16.0.1