twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/src/FrontApp/Infrastructure/View': ~
    globals:
        reports_url: '%env(REPORTS_URL)%'

when@test:
    twig:
        strict_variables: true
