update cod_dane set courier = 'SUR' where code = '73443';
update cod_dane set courier = 'EJE CAFETERO' where code = '66045';
update cod_dane set courier = 'SUR' where code = '41791';
update cod_dane set courier = 'ORIENTE' where code = '20310';
update cod_dane set courier = 'SUR' where code = '73585';
update cod_dane set courier = 'ORIENTE' where code = '68276';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05001';
update cod_dane set courier = 'EJE CAFETERO' where code = '17873';
update cod_dane set courier = 'CENTRO B' where code = '15723';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05113';
update cod_dane set courier = 'ORIENTE' where code = '54520';
update cod_dane set courier = 'OCCIDENTE' where code = '19693';
update cod_dane set courier = 'EJE CAFETERO' where code = '17486';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05240';
update cod_dane set courier = 'NORTE' where code = '70429';
update cod_dane set courier = 'CENTRO B' where code = '50287';
update cod_dane set courier = 'SUR' where code = '18256';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05361';
update cod_dane set courier = 'CENTRO B' where code = '25807';
update cod_dane set courier = 'OCCIDENTE' where code = '52506';
update cod_dane set courier = 'CENTRO B' where code = '91798';
update cod_dane set courier = 'ORIENTE' where code = '81736';
update cod_dane set courier = 'CENTRO B' where code = '85325';
update cod_dane set courier = 'SUR' where code = '73024';
update cod_dane set courier = 'CENTRO B' where code = '25299';
update cod_dane set courier = 'OCCIDENTE' where code = '76250';
update cod_dane set courier = 'ORIENTE' where code = '54313';
update cod_dane set courier = 'ORIENTE' where code = '54871';
update cod_dane set courier = 'NORTE' where code = '08758';
update cod_dane set courier = 'OCCIDENTE' where code = '52287';
update cod_dane set courier = 'EJE CAFETERO' where code = '17380';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27025';
update cod_dane set courier = 'CENTRO B' where code = '15804';
update cod_dane set courier = 'CENTRO B' where code = '25572';
update cod_dane set courier = 'CENTRO B' where code = '50110';
update cod_dane set courier = 'SUR' where code = '41548';
update cod_dane set courier = 'NORTE' where code = '08520';
update cod_dane set courier = 'OCCIDENTE' where code = '19698';
update cod_dane set courier = 'CENTRO B' where code = '25793';
update cod_dane set courier = 'CENTRO B' where code = '15676';
update cod_dane set courier = 'CENTRO B' where code = '25019';
update cod_dane set courier = 'SUR' where code = '41306';
update cod_dane set courier = 'ORIENTE' where code = '68575';
update cod_dane set courier = 'ORIENTE' where code = '68755';
update cod_dane set courier = 'ORIENTE' where code = '54673';
update cod_dane set courier = 'OCCIDENTE' where code = '52838';
update cod_dane set courier = 'CENTRO B' where code = '15778';
update cod_dane set courier = 'CENTRO B' where code = '15514';
update cod_dane set courier = 'NORTE' where code = '44650';
update cod_dane set courier = 'EJE CAFETERO' where code = '66088';
update cod_dane set courier = 'CENTRO B' where code = '25154';
update cod_dane set courier = 'NORTE' where code = '08675';
update cod_dane set courier = 'EJE CAFETERO' where code = '63302';
update cod_dane set courier = 'ORIENTE' where code = '68425';
update cod_dane set courier = 'CENTRO B' where code = '15806';
update cod_dane set courier = 'SUR' where code = '41001';
update cod_dane set courier = 'SUR' where code = '73686';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05686';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05642';
update cod_dane set courier = 'NORTE' where code = '70418';
update cod_dane set courier = 'NORTE' where code = '70221';
update cod_dane set courier = 'OCCIDENTE' where code = '76243';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05660';
update cod_dane set courier = 'CENTRO B' where code = '25120';
update cod_dane set courier = 'NORTE' where code = '08078';
update cod_dane set courier = 'NORTE' where code = '70230';
update cod_dane set courier = 'OCCIDENTE' where code = '52621';
update cod_dane set courier = 'CENTRO B' where code = '15380';
update cod_dane set courier = 'ORIENTE' where code = '68770';
update cod_dane set courier = 'NORTE' where code = '23660';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05631';
update cod_dane set courier = 'ORIENTE' where code = '68368';
update cod_dane set courier = 'NORTE' where code = '13838';
update cod_dane set courier = 'NORTE' where code = '08001';
update cod_dane set courier = 'ORIENTE' where code = '54800';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05400';
update cod_dane set courier = 'SUR' where code = '41396';
update cod_dane set courier = 'NORTE' where code = '13244';
update cod_dane set courier = 'ORIENTE' where code = '68207';
update cod_dane set courier = 'ORIENTE' where code = '54670';
update cod_dane set courier = 'OCCIDENTE' where code = '76892';
update cod_dane set courier = 'OCCIDENTE' where code = '19760';
update cod_dane set courier = 'ORIENTE' where code = '20517';
update cod_dane set courier = 'OCCIDENTE' where code = '19807';
update cod_dane set courier = 'CENTRO B' where code = '15491';
update cod_dane set courier = 'SUR' where code = '73671';
update cod_dane set courier = 'NORTE' where code = '23189';
update cod_dane set courier = 'NORTE' where code = '13836';
update cod_dane set courier = 'CENTRO B' where code = '25779';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05036';
update cod_dane set courier = 'CENTRO B' where code = '85430';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05034';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05129';
update cod_dane set courier = 'CENTRO B' where code = '50350';
update cod_dane set courier = 'ORIENTE' where code = '81001';
update cod_dane set courier = 'CENTRO B' where code = '15500';
update cod_dane set courier = 'OCCIDENTE' where code = '19050';
update cod_dane set courier = 'OCCIDENTE' where code = '19450';
update cod_dane set courier = 'CENTRO B' where code = '94883';
update cod_dane set courier = 'ORIENTE' where code = '54245';
update cod_dane set courier = 'EJE CAFETERO' where code = '17877';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05607';
update cod_dane set courier = 'CENTRO B' where code = '15215';
update cod_dane set courier = 'OCCIDENTE' where code = '76275';
update cod_dane set courier = 'ORIENTE' where code = '68502';
update cod_dane set courier = 'SUR' where code = '41660';
update cod_dane set courier = 'OCCIDENTE' where code = '52694';
update cod_dane set courier = 'ORIENTE' where code = '54125';
update cod_dane set courier = 'ORIENTE' where code = '68318';
update cod_dane set courier = 'CENTRO B' where code = '15693';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05021';
update cod_dane set courier = 'OCCIDENTE' where code = '76845';
update cod_dane set courier = 'NORTE' where code = '23001';
update cod_dane set courier = 'NORTE' where code = '13670';
update cod_dane set courier = 'CENTRO B' where code = '15646';
update cod_dane set courier = 'NORTE' where code = '70235';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05411';
update cod_dane set courier = 'ORIENTE' where code = '54174';
update cod_dane set courier = 'NORTE' where code = '47161';
update cod_dane set courier = 'CENTRO B' where code = '25317';
update cod_dane set courier = 'SUR' where code = '73055';
update cod_dane set courier = 'CENTRO B' where code = '15322';
update cod_dane set courier = 'CENTRO B' where code = '15244';
update cod_dane set courier = 'CENTRO B' where code = '88564';
update cod_dane set courier = 'CENTRO B' where code = '15131';
update cod_dane set courier = 'ORIENTE' where code = '54398';
update cod_dane set courier = 'CENTRO B' where code = '50223';
update cod_dane set courier = 'CENTRO B' where code = '15667';
update cod_dane set courier = 'CENTRO B' where code = '50150';
update cod_dane set courier = 'ORIENTE' where code = '20032';
update cod_dane set courier = 'NORTE' where code = '13744';
update cod_dane set courier = 'CENTRO B' where code = '25649';
update cod_dane set courier = 'CENTRO B' where code = '25867';
update cod_dane set courier = 'CENTRO B' where code = '25307';
update cod_dane set courier = 'OCCIDENTE' where code = '19075';
update cod_dane set courier = 'CENTRO B' where code = '15820';
update cod_dane set courier = 'EJE CAFETERO' where code = '17388';
update cod_dane set courier = 'CENTRO B' where code = '85136';
update cod_dane set courier = 'NORTE' where code = '23500';
update cod_dane set courier = 'NORTE' where code = '13442';
update cod_dane set courier = 'OCCIDENTE' where code = '52390';
update cod_dane set courier = 'OCCIDENTE' where code = '76036';
update cod_dane set courier = 'EJE CAFETERO' where code = '63548';
update cod_dane set courier = 'OCCIDENTE' where code = '52019';
update cod_dane set courier = 'NORTE' where code = '47030';
update cod_dane set courier = 'NORTE' where code = '44560';
update cod_dane set courier = 'NORTE' where code = '08558';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05376';
update cod_dane set courier = 'EJE CAFETERO' where code = '66594';
update cod_dane set courier = 'NORTE' where code = '47318';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05145';
update cod_dane set courier = 'ORIENTE' where code = '68211';
update cod_dane set courier = 'ORIENTE' where code = '54003';
update cod_dane set courier = 'CENTRO B' where code = '25862';
update cod_dane set courier = 'CENTRO B' where code = '15686';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05148';
update cod_dane set courier = 'CENTRO B' where code = '15816';
update cod_dane set courier = 'ORIENTE' where code = '54874';
update cod_dane set courier = 'OCCIDENTE' where code = '19001';
update cod_dane set courier = 'CENTRO B' where code = '15531';
update cod_dane set courier = 'SUR' where code = '18592';
update cod_dane set courier = 'OCCIDENTE' where code = '19473';
update cod_dane set courier = 'CENTRO B' where code = '95015';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05347';
update cod_dane set courier = 'CENTRO B' where code = '50330';
update cod_dane set courier = 'OCCIDENTE' where code = '52418';
update cod_dane set courier = 'NORTE' where code = '13160';
update cod_dane set courier = 'NORTE' where code = '23168';
update cod_dane set courier = 'ORIENTE' where code = '68324';
update cod_dane set courier = 'ORIENTE' where code = '54518';
update cod_dane set courier = 'NORTE' where code = '08549';
update cod_dane set courier = 'CENTRO B' where code = '25279';
update cod_dane set courier = 'CENTRO B' where code = '25377';
update cod_dane set courier = 'CENTRO B' where code = '25286';
update cod_dane set courier = 'NORTE' where code = '08560';
update cod_dane set courier = 'CENTRO B' where code = '50683';
update cod_dane set courier = 'OCCIDENTE' where code = '19780';
update cod_dane set courier = 'CENTRO B' where code = '85001';
update cod_dane set courier = 'EJE CAFETERO' where code = '63470';
update cod_dane set courier = 'CENTRO B' where code = '15455';
update cod_dane set courier = 'NORTE' where code = '23162';
update cod_dane set courier = 'EJE CAFETERO' where code = '63401';
update cod_dane set courier = 'CENTRO B' where code = '88001';
update cod_dane set courier = 'CENTRO B' where code = '95200';
update cod_dane set courier = 'CENTRO B' where code = '15442';
update cod_dane set courier = 'NORTE' where code = '70400';
update cod_dane set courier = 'CENTRO B' where code = '25151';
update cod_dane set courier = 'ORIENTE' where code = '20175';
update cod_dane set courier = 'CENTRO B' where code = '15542';
update cod_dane set courier = 'NORTE' where code = '23417';
update cod_dane set courier = 'NORTE' where code = '13458';
update cod_dane set courier = 'CENTRO B' where code = '97889';
update cod_dane set courier = 'EJE CAFETERO' where code = '17444';
update cod_dane set courier = 'SUR' where code = '41797';
update cod_dane set courier = 'ORIENTE' where code = '68092';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27430';
update cod_dane set courier = 'CENTRO B' where code = '94886';
update cod_dane set courier = 'OCCIDENTE' where code = '19397';
update cod_dane set courier = 'CENTRO B' where code = '25035';
update cod_dane set courier = 'OCCIDENTE' where code = '19100';
update cod_dane set courier = 'CENTRO B' where code = '25312';
update cod_dane set courier = 'CENTRO B' where code = '25658';
update cod_dane set courier = 'OCCIDENTE' where code = '52207';
update cod_dane set courier = 'ORIENTE' where code = '81794';
update cod_dane set courier = 'ORIENTE' where code = '68385';
update cod_dane set courier = 'ORIENTE' where code = '68464';
update cod_dane set courier = 'ORIENTE' where code = '68245';
update cod_dane set courier = 'CENTRO B' where code = '25885';
update cod_dane set courier = 'OCCIDENTE' where code = '52215';
update cod_dane set courier = 'CENTRO B' where code = '25295';
update cod_dane set courier = 'NORTE' where code = '08770';
update cod_dane set courier = 'OCCIDENTE' where code = '52699';
update cod_dane set courier = 'CENTRO B' where code = '50124';
update cod_dane set courier = 'ORIENTE' where code = '54660';
update cod_dane set courier = 'OCCIDENTE' where code = '76041';
update cod_dane set courier = 'CENTRO B' where code = '25851';
update cod_dane set courier = 'EJE CAFETERO' where code = '17050';
update cod_dane set courier = 'CENTRO B' where code = '15172';
update cod_dane set courier = 'OCCIDENTE' where code = '76736';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27160';
update cod_dane set courier = 'SUR' where code = '73520';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27075';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05045';
update cod_dane set courier = 'SUR' where code = '41359';
update cod_dane set courier = 'CENTRO B' where code = '25899';
update cod_dane set courier = 'CENTRO B' where code = '15814';
update cod_dane set courier = 'CENTRO B' where code = '97777';
update cod_dane set courier = 'CENTRO B' where code = '25290';
update cod_dane set courier = 'EJE CAFETERO' where code = '17001';
update cod_dane set courier = 'SUR' where code = '73461';
update cod_dane set courier = 'ORIENTE' where code = '54128';
update cod_dane set courier = 'CENTRO B' where code = '91460';
update cod_dane set courier = 'CENTRO B' where code = '25718';
update cod_dane set courier = 'CENTRO B' where code = '50006';
update cod_dane set courier = 'CENTRO B' where code = '15425';
update cod_dane set courier = 'CENTRO B' where code = '25320';
update cod_dane set courier = 'CENTRO B' where code = '15839';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05002';
update cod_dane set courier = 'SUR' where code = '73319';
update cod_dane set courier = 'OCCIDENTE' where code = '52256';
update cod_dane set courier = 'CENTRO B' where code = '25799';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05315';
update cod_dane set courier = 'CENTRO B' where code = '15001';
update cod_dane set courier = 'CENTRO B' where code = '15808';
update cod_dane set courier = 'CENTRO B' where code = '25269';
update cod_dane set courier = 'OCCIDENTE' where code = '19355';
update cod_dane set courier = 'CENTRO B' where code = '25326';
update cod_dane set courier = 'CENTRO B' where code = '25772';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05172';
update cod_dane set courier = 'CENTRO B' where code = '25841';
update cod_dane set courier = 'ORIENTE' where code = '20443';
update cod_dane set courier = 'ORIENTE' where code = '54743';
update cod_dane set courier = 'CENTRO B' where code = '25817';
update cod_dane set courier = 'ORIENTE' where code = '20570';
update cod_dane set courier = 'OCCIDENTE' where code = '52435';
update cod_dane set courier = 'SUR' where code = '41016';
update cod_dane set courier = 'OCCIDENTE' where code = '19418';
update cod_dane set courier = 'EJE CAFETERO' where code = '17495';
update cod_dane set courier = 'CENTRO B' where code = '15097';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27580';
update cod_dane set courier = 'CENTRO B' where code = '25489';
update cod_dane set courier = 'CENTRO B' where code = '15480';
update cod_dane set courier = 'NORTE' where code = '13600';
update cod_dane set courier = 'OCCIDENTE' where code = '76147';
update cod_dane set courier = 'CENTRO B' where code = '25797';
update cod_dane set courier = 'OCCIDENTE' where code = '76246';
update cod_dane set courier = 'SUR' where code = '41799';
update cod_dane set courier = 'ORIENTE' where code = '68855';
update cod_dane set courier = 'CENTRO B' where code = '15790';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05004';
update cod_dane set courier = 'CENTRO B' where code = '25372';
update cod_dane set courier = 'CENTRO B' where code = '50313';
update cod_dane set courier = 'OCCIDENTE' where code = '52585';
update cod_dane set courier = 'NORTE' where code = '08638';
update cod_dane set courier = 'CENTRO B' where code = '25754';
update cod_dane set courier = 'CENTRO B' where code = '15638';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05679';
update cod_dane set courier = 'NORTE' where code = '44090';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05665';
update cod_dane set courier = 'CENTRO B' where code = '25769';
update cod_dane set courier = 'NORTE' where code = '13667';
update cod_dane set courier = 'NORTE' where code = '23350';
update cod_dane set courier = 'SUR' where code = '73148';
update cod_dane set courier = 'OCCIDENTE' where code = '52678';
update cod_dane set courier = 'CENTRO B' where code = '91407';
update cod_dane set courier = 'EJE CAFETERO' where code = '66456';
update cod_dane set courier = 'ORIENTE' where code = '68255';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05790';
update cod_dane set courier = 'CENTRO B' where code = '15550';
update cod_dane set courier = 'OCCIDENTE' where code = '52490';
update cod_dane set courier = 'CENTRO B' where code = '15176';
update cod_dane set courier = 'SUR' where code = '41357';
update cod_dane set courier = 'SUR' where code = '73483';
update cod_dane set courier = 'ORIENTE' where code = '68264';
update cod_dane set courier = 'CENTRO B' where code = '15226';
update cod_dane set courier = 'SUR' where code = '73449';
update cod_dane set courier = 'CENTRO B' where code = '15092';
update cod_dane set courier = 'NORTE' where code = '47053';
update cod_dane set courier = 'SUR' where code = '73067';
update cod_dane set courier = 'CENTRO B' where code = '85225';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05150';
update cod_dane set courier = 'NORTE' where code = '23300';
update cod_dane set courier = 'NORTE' where code = '23182';
update cod_dane set courier = 'CENTRO B' where code = '15362';
update cod_dane set courier = 'CENTRO B' where code = '15774';
update cod_dane set courier = 'ORIENTE' where code = '68524';
update cod_dane set courier = 'NORTE' where code = '13222';
update cod_dane set courier = 'CENTRO B' where code = '85440';
update cod_dane set courier = 'SUR' where code = '73616';
update cod_dane set courier = 'CENTRO B' where code = '25898';
update cod_dane set courier = 'OCCIDENTE' where code = '76497';
update cod_dane set courier = 'CENTRO B' where code = '15761';
update cod_dane set courier = 'CENTRO B' where code = '91536';
update cod_dane set courier = 'NORTE' where code = '13810';
update cod_dane set courier = 'CENTRO B' where code = '50251';
update cod_dane set courier = 'CENTRO B' where code = '15368';
update cod_dane set courier = 'CENTRO B' where code = '94884';
update cod_dane set courier = 'NORTE' where code = '47980';
update cod_dane set courier = 'CENTRO B' where code = '94001';
update cod_dane set courier = 'OCCIDENTE' where code = '19517';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27135';
update cod_dane set courier = 'SUR' where code = '18247';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05093';
update cod_dane set courier = 'CENTRO B' where code = '25530';
update cod_dane set courier = 'CENTRO B' where code = '85263';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27001';
update cod_dane set courier = 'EJE CAFETERO' where code = '66440';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05628';
update cod_dane set courier = 'NORTE' where code = '13894';
update cod_dane set courier = 'CENTRO B' where code = '15764';
update cod_dane set courier = 'OCCIDENTE' where code = '76109';
update cod_dane set courier = 'SUR' where code = '18150';
update cod_dane set courier = 'ORIENTE' where code = '54239';
update cod_dane set courier = 'SUR' where code = '73001';
update cod_dane set courier = 'NORTE' where code = '08137';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05250';
update cod_dane set courier = 'NORTE' where code = '47675';
update cod_dane set courier = 'CENTRO B' where code = '15469';
update cod_dane set courier = 'OCCIDENTE' where code = '19455';
update cod_dane set courier = 'CENTRO B' where code = '15776';
update cod_dane set courier = 'CENTRO B' where code = '50606';
update cod_dane set courier = 'NORTE' where code = '47745';
update cod_dane set courier = 'OCCIDENTE' where code = '19532';
update cod_dane set courier = 'ORIENTE' where code = '54001';
update cod_dane set courier = 'SUR' where code = '73275';
update cod_dane set courier = 'CENTRO B' where code = '50270';
update cod_dane set courier = 'CENTRO B' where code = '25324';
update cod_dane set courier = 'ORIENTE' where code = '20238';
update cod_dane set courier = 'ORIENTE' where code = '68370';
update cod_dane set courier = 'CENTRO B' where code = '50573';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05467';
update cod_dane set courier = 'SUR' where code = '18410';
update cod_dane set courier = 'OCCIDENTE' where code = '76364';
update cod_dane set courier = 'CENTRO B' where code = '15696';
update cod_dane set courier = 'CENTRO B' where code = '15022';
update cod_dane set courier = 'OCCIDENTE' where code = '76054';
update cod_dane set courier = 'CENTRO B' where code = '25781';
update cod_dane set courier = 'NORTE' where code = '70473';
update cod_dane set courier = 'ORIENTE' where code = '68001';
update cod_dane set courier = 'ORIENTE' where code = '68572';
update cod_dane set courier = 'CENTRO B' where code = '25513';
update cod_dane set courier = 'ORIENTE' where code = '20295';
update cod_dane set courier = 'CENTRO B' where code = '85315';
update cod_dane set courier = 'CENTRO B' where code = '25178';
update cod_dane set courier = 'SUR' where code = '41319';
update cod_dane set courier = 'ORIENTE' where code = '68250';
update cod_dane set courier = 'CENTRO B' where code = '50245';
update cod_dane set courier = 'ORIENTE' where code = '68615';
update cod_dane set courier = 'OCCIDENTE' where code = '52560';
update cod_dane set courier = 'NORTE' where code = '47551';
update cod_dane set courier = 'ORIENTE' where code = '20001';
update cod_dane set courier = 'NORTE' where code = '23586';
update cod_dane set courier = 'OCCIDENTE' where code = '52786';
update cod_dane set courier = 'NORTE' where code = '47707';
update cod_dane set courier = 'ORIENTE' where code = '54553';
update cod_dane set courier = 'CENTRO B' where code = '15051';
update cod_dane set courier = 'CENTRO B' where code = '25839';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05142';
update cod_dane set courier = 'CENTRO B' where code = '25281';
update cod_dane set courier = 'NORTE' where code = '13430';
update cod_dane set courier = 'CENTRO B' where code = '50226';
update cod_dane set courier = 'CENTRO B' where code = '85230';
update cod_dane set courier = 'ORIENTE' where code = '68307';
update cod_dane set courier = 'CENTRO B' where code = '15511';
update cod_dane set courier = 'NORTE' where code = '13655';
update cod_dane set courier = 'SUR' where code = '73504';
update cod_dane set courier = 'OCCIDENTE' where code = '52260';
update cod_dane set courier = 'NORTE' where code = '23570';
update cod_dane set courier = 'OCCIDENTE' where code = '52227';
update cod_dane set courier = 'ORIENTE' where code = '54810';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27450';
update cod_dane set courier = 'ORIENTE' where code = '20710';
update cod_dane set courier = 'SUR' where code = '73555';
update cod_dane set courier = 'CENTRO B' where code = '97511';
update cod_dane set courier = 'OCCIDENTE' where code = '52378';
update cod_dane set courier = 'CENTRO B' where code = '25843';
update cod_dane set courier = 'OCCIDENTE' where code = '76233';
update cod_dane set courier = 'EJE CAFETERO' where code = '63111';
update cod_dane set courier = 'OCCIDENTE' where code = '19785';
update cod_dane set courier = 'EJE CAFETERO' where code = '17272';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05234';
update cod_dane set courier = 'CENTRO B' where code = '25878';
update cod_dane set courier = 'OCCIDENTE' where code = '52381';
update cod_dane set courier = 'NORTE' where code = '44279';
update cod_dane set courier = 'CENTRO B' where code = '15248';
update cod_dane set courier = 'CENTRO B' where code = '50577';
update cod_dane set courier = 'SUR' where code = '18860';
update cod_dane set courier = 'ORIENTE' where code = '68344';
update cod_dane set courier = 'ORIENTE' where code = '68179';
update cod_dane set courier = 'CENTRO B' where code = '25430';
update cod_dane set courier = 'SUR' where code = '73152';
update cod_dane set courier = 'CENTRO B' where code = '15276';
update cod_dane set courier = 'OCCIDENTE' where code = '76306';
update cod_dane set courier = 'NORTE' where code = '08433';
update cod_dane set courier = 'EJE CAFETERO' where code = '66383';
update cod_dane set courier = 'OCCIDENTE' where code = '76606';
update cod_dane set courier = 'CENTRO B' where code = '25245';
update cod_dane set courier = 'CENTRO B' where code = '85400';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27491';
update cod_dane set courier = 'CENTRO B' where code = '15183';
update cod_dane set courier = 'CENTRO B' where code = '25745';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05670';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27800';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05667';
update cod_dane set courier = 'SUR' where code = '73411';
update cod_dane set courier = 'CENTRO B' where code = '50450';
update cod_dane set courier = 'EJE CAFETERO' where code = '17433';
update cod_dane set courier = 'NORTE' where code = '13683';
update cod_dane set courier = 'NORTE' where code = '13212';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05440';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05197';
update cod_dane set courier = 'NORTE' where code = '13140';
update cod_dane set courier = 'OCCIDENTE' where code = '19022';
update cod_dane set courier = 'NORTE' where code = '47258';
update cod_dane set courier = 'CENTRO B' where code = '15832';
update cod_dane set courier = 'CENTRO B' where code = '85015';
update cod_dane set courier = 'EJE CAFETERO' where code = '17088';
update cod_dane set courier = 'NORTE' where code = '23090';
update cod_dane set courier = 'EJE CAFETERO' where code = '17662';
update cod_dane set courier = 'CENTRO B' where code = '15681';
update cod_dane set courier = 'NORTE' where code = '13030';
update cod_dane set courier = 'CENTRO B' where code = '99001';
update cod_dane set courier = 'EJE CAFETERO' where code = '63690';
update cod_dane set courier = 'OCCIDENTE' where code = '76403';
update cod_dane set courier = 'ORIENTE' where code = '68079';
update cod_dane set courier = 'OCCIDENTE' where code = '52224';
update cod_dane set courier = 'CENTRO B' where code = '99524';
update cod_dane set courier = 'ORIENTE' where code = '68397';
update cod_dane set courier = 'CENTRO B' where code = '50686';
update cod_dane set courier = 'ORIENTE' where code = '81065';
update cod_dane set courier = 'OCCIDENTE' where code = '19548';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05031';
update cod_dane set courier = 'NORTE' where code = '70508';
update cod_dane set courier = 'NORTE' where code = '47555';
update cod_dane set courier = 'CENTRO B' where code = '15507';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05761';
update cod_dane set courier = 'CENTRO B' where code = '25518';
update cod_dane set courier = 'ORIENTE' where code = '54377';
update cod_dane set courier = 'SUR' where code = '18001';
update cod_dane set courier = 'ORIENTE' where code = '20750';
update cod_dane set courier = 'CENTRO B' where code = '25322';
update cod_dane set courier = 'SUR' where code = '73030';
update cod_dane set courier = 'CENTRO B' where code = '15464';
update cod_dane set courier = 'ORIENTE' where code = '81220';
update cod_dane set courier = 'CENTRO B' where code = '25001';
update cod_dane set courier = 'NORTE' where code = '44430';
update cod_dane set courier = 'CENTRO B' where code = '15810';
update cod_dane set courier = 'NORTE' where code = '23419';
update cod_dane set courier = 'ORIENTE' where code = '54599';
update cod_dane set courier = 'OCCIDENTE' where code = '52683';
update cod_dane set courier = 'CENTRO B' where code = '25662';
update cod_dane set courier = 'OCCIDENTE' where code = '52473';
update cod_dane set courier = 'NORTE' where code = '13042';
update cod_dane set courier = 'SUR' where code = '41676';
update cod_dane set courier = 'OCCIDENTE' where code = '19110';
update cod_dane set courier = 'ORIENTE' where code = '68720';
update cod_dane set courier = 'OCCIDENTE' where code = '52320';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05591';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05885';
update cod_dane set courier = 'OCCIDENTE' where code = '52612';
update cod_dane set courier = 'NORTE' where code = '08296';
update cod_dane set courier = 'SUR' where code = '73043';
update cod_dane set courier = 'CENTRO A' where code = '11001';
update cod_dane set courier = 'OCCIDENTE' where code = '52317';
update cod_dane set courier = 'ORIENTE' where code = '54261';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27150';
update cod_dane set courier = 'CENTRO B' where code = '91001';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05541';
update cod_dane set courier = 'ORIENTE' where code = '68669';
update cod_dane set courier = 'NORTE' where code = '47605';
update cod_dane set courier = 'SUR' where code = '73200';
update cod_dane set courier = 'NORTE' where code = '13001';
update cod_dane set courier = 'ORIENTE' where code = '68498';
update cod_dane set courier = 'CENTRO B' where code = '15753';
update cod_dane set courier = 'NORTE' where code = '08421';
update cod_dane set courier = 'CENTRO B' where code = '25181';
update cod_dane set courier = 'NORTE' where code = '70771';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27810';
update cod_dane set courier = 'EJE CAFETERO' where code = '17013';
update cod_dane set courier = 'NORTE' where code = '47692';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05134';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05209';
update cod_dane set courier = 'NORTE' where code = '13268';
update cod_dane set courier = 'CENTRO B' where code = '15476';
update cod_dane set courier = 'CENTRO B' where code = '25394';
update cod_dane set courier = 'SUR' where code = '41872';
update cod_dane set courier = 'CENTRO B' where code = '15087';
update cod_dane set courier = 'EJE CAFETERO' where code = '63130';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05664';
update cod_dane set courier = 'OCCIDENTE' where code = '76863';
update cod_dane set courier = 'OCCIDENTE' where code = '52685';
update cod_dane set courier = 'OCCIDENTE' where code = '52411';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05390';
update cod_dane set courier = 'OCCIDENTE' where code = '76126';
update cod_dane set courier = 'CENTRO B' where code = '25524';
update cod_dane set courier = 'ORIENTE' where code = '68432';
update cod_dane set courier = 'ORIENTE' where code = '54405';
update cod_dane set courier = 'ORIENTE' where code = '54051';
update cod_dane set courier = 'NORTE' where code = '13248';
update cod_dane set courier = 'CENTRO B' where code = '25596';
update cod_dane set courier = 'OCCIDENTE' where code = '76130';
update cod_dane set courier = 'CENTRO B' where code = '15223';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27006';
update cod_dane set courier = 'OCCIDENTE' where code = '76622';
update cod_dane set courier = 'NORTE' where code = '13780';
update cod_dane set courier = 'SUR' where code = '73408';
update cod_dane set courier = 'ORIENTE' where code = '68322';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27250';
update cod_dane set courier = 'ORIENTE' where code = '68549';
update cod_dane set courier = 'SUR' where code = '41524';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05837';
update cod_dane set courier = 'CENTRO B' where code = '15664';
update cod_dane set courier = 'OCCIDENTE' where code = '52427';
update cod_dane set courier = 'SUR' where code = '41807';
update cod_dane set courier = 'OCCIDENTE' where code = '76670';
update cod_dane set courier = 'OCCIDENTE' where code = '19364';
update cod_dane set courier = 'EJE CAFETERO' where code = '17541';
update cod_dane set courier = 'OCCIDENTE' where code = '52254';
update cod_dane set courier = 'NORTE' where code = '47170';
update cod_dane set courier = 'ORIENTE' where code = '68522';
update cod_dane set courier = 'SUR' where code = '41349';
update cod_dane set courier = 'OCCIDENTE' where code = '76020';
update cod_dane set courier = 'NORTE' where code = '70233';
update cod_dane set courier = 'EJE CAFETERO' where code = '17524';
update cod_dane set courier = 'ORIENTE' where code = '20787';
update cod_dane set courier = 'EJE CAFETERO' where code = '66682';
update cod_dane set courier = 'NORTE' where code = '70124';
update cod_dane set courier = 'CENTRO B' where code = '25200';
update cod_dane set courier = 'SUR' where code = '18479';
update cod_dane set courier = 'CENTRO B' where code = '15673';
update cod_dane set courier = 'NORTE' where code = '08849';
update cod_dane set courier = 'OCCIDENTE' where code = '52240';
update cod_dane set courier = 'SUR' where code = '41298';
update cod_dane set courier = 'NORTE' where code = '08436';
update cod_dane set courier = 'EJE CAFETERO' where code = '66001';
update cod_dane set courier = 'NORTE' where code = '13647';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05107';
update cod_dane set courier = 'CENTRO B' where code = '15104';
update cod_dane set courier = 'OCCIDENTE' where code = '19701';
update cod_dane set courier = 'CENTRO B' where code = '15522';
update cod_dane set courier = 'CENTRO B' where code = '85139';
update cod_dane set courier = 'CENTRO B' where code = '15293';
update cod_dane set courier = 'NORTE' where code = '23807';
update cod_dane set courier = 'NORTE' where code = '44001';
update cod_dane set courier = 'OCCIDENTE' where code = '76823';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05893';
update cod_dane set courier = 'CENTRO B' where code = '25592';
update cod_dane set courier = 'SUR' where code = '73622';
update cod_dane set courier = 'NORTE' where code = '13760';
update cod_dane set courier = 'CENTRO B' where code = '15296';
update cod_dane set courier = 'OCCIDENTE' where code = '52480';
update cod_dane set courier = 'NORTE' where code = '47798';
update cod_dane set courier = 'EJE CAFETERO' where code = '17653';
update cod_dane set courier = 'ORIENTE' where code = '68271';
update cod_dane set courier = 'OCCIDENTE' where code = '19743';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05120';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05364';
update cod_dane set courier = 'ORIENTE' where code = '68745';
update cod_dane set courier = 'CENTRO B' where code = '25224';
update cod_dane set courier = 'NORTE' where code = '47245';
update cod_dane set courier = 'ORIENTE' where code = '20060';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05308';
update cod_dane set courier = 'CENTRO B' where code = '25053';
update cod_dane set courier = 'NORTE' where code = '47288';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05495';
update cod_dane set courier = 'CENTRO B' where code = '50711';
update cod_dane set courier = 'NORTE' where code = '08372';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05819';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27495';
update cod_dane set courier = 'ORIENTE' where code = '68162';
update cod_dane set courier = 'ORIENTE' where code = '20621';
update cod_dane set courier = 'ORIENTE' where code = '54720';
update cod_dane set courier = 'ORIENTE' where code = '68190';
update cod_dane set courier = 'CENTRO B' where code = '25386';
update cod_dane set courier = 'NORTE' where code = '23678';
update cod_dane set courier = 'CENTRO B' where code = '15533';
update cod_dane set courier = 'EJE CAFETERO' where code = '63272';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27600';
update cod_dane set courier = 'CENTRO B' where code = '25594';
update cod_dane set courier = 'EJE CAFETERO' where code = '17616';
update cod_dane set courier = 'ORIENTE' where code = '68533';
update cod_dane set courier = 'NORTE' where code = '70742';
update cod_dane set courier = 'ORIENTE' where code = '54820';
update cod_dane set courier = 'CENTRO B' where code = '15518';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05792';
update cod_dane set courier = 'CENTRO B' where code = '94887';
update cod_dane set courier = 'OCCIDENTE' where code = '52354';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05789';
update cod_dane set courier = 'ORIENTE' where code = '20770';
update cod_dane set courier = 'OCCIDENTE' where code = '76100';
update cod_dane set courier = 'NORTE' where code = '44420';
update cod_dane set courier = 'NORTE' where code = '23068';
update cod_dane set courier = 'CENTRO B' where code = '15232';
update cod_dane set courier = 'ORIENTE' where code = '68020';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05086';
update cod_dane set courier = 'SUR' where code = '41668';
update cod_dane set courier = 'ORIENTE' where code = '68051';
update cod_dane set courier = 'OCCIDENTE' where code = '52022';
update cod_dane set courier = 'CENTRO B' where code = '25758';
update cod_dane set courier = 'SUR' where code = '73873';
update cod_dane set courier = 'CENTRO B' where code = '97001';
update cod_dane set courier = 'CENTRO B' where code = '15403';
update cod_dane set courier = 'CENTRO B' where code = '91263';
update cod_dane set courier = 'ORIENTE' where code = '68444';
update cod_dane set courier = 'ORIENTE' where code = '68229';
update cod_dane set courier = 'OCCIDENTE' where code = '19137';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05079';
update cod_dane set courier = 'SUR' where code = '73349';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05483';
update cod_dane set courier = 'CENTRO B' where code = '50325';
update cod_dane set courier = 'OCCIDENTE' where code = '19821';
update cod_dane set courier = 'OCCIDENTE' where code = '19130';
update cod_dane set courier = 'NORTE' where code = '13440';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05030';
update cod_dane set courier = 'CENTRO B' where code = '91405';
update cod_dane set courier = 'NORTE' where code = '70717';
update cod_dane set courier = 'NORTE' where code = '47960';
update cod_dane set courier = 'CENTRO B' where code = '15861';
update cod_dane set courier = 'SUR' where code = '41378';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05264';
update cod_dane set courier = 'ORIENTE' where code = '54099';
update cod_dane set courier = 'ORIENTE' where code = '68773';
update cod_dane set courier = 'CENTRO B' where code = '50568';
update cod_dane set courier = 'NORTE' where code = '47720';
update cod_dane set courier = 'ORIENTE' where code = '20550';
update cod_dane set courier = 'ORIENTE' where code = '68673';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05861';
update cod_dane set courier = 'ORIENTE' where code = '68132';
update cod_dane set courier = 'NORTE' where code = '47268';
update cod_dane set courier = 'ORIENTE' where code = '68121';
update cod_dane set courier = 'ORIENTE' where code = '68152';
update cod_dane set courier = 'OCCIDENTE' where code = '52696';
update cod_dane set courier = 'EJE CAFETERO' where code = '66170';
update cod_dane set courier = 'CENTRO B' where code = '15106';
update cod_dane set courier = 'NORTE' where code = '13688';
update cod_dane set courier = 'ORIENTE' where code = '20383';
update cod_dane set courier = 'NORTE' where code = '47001';
update cod_dane set courier = 'CENTRO B' where code = '25123';
update cod_dane set courier = 'CENTRO B' where code = '15299';
update cod_dane set courier = 'SUR' where code = '18785';
update cod_dane set courier = 'CENTRO B' where code = '25148';
update cod_dane set courier = 'NORTE' where code = '70678';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27745';
update cod_dane set courier = 'NORTE' where code = '47545';
update cod_dane set courier = 'NORTE' where code = '70713';
update cod_dane set courier = 'NORTE' where code = '44035';
update cod_dane set courier = 'OCCIDENTE' where code = '19533';
update cod_dane set courier = 'CENTRO B' where code = '15897';
update cod_dane set courier = 'CENTRO B' where code = '25398';
update cod_dane set courier = 'ORIENTE' where code = '68686';
update cod_dane set courier = 'SUR' where code = '41132';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05380';
update cod_dane set courier = 'CENTRO B' where code = '15189';
update cod_dane set courier = 'SUR' where code = '18610';
update cod_dane set courier = 'NORTE' where code = '08141';
update cod_dane set courier = 'SUR' where code = '41206';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27413';
update cod_dane set courier = 'NORTE' where code = '70670';
update cod_dane set courier = 'CENTRO B' where code = '25483';
update cod_dane set courier = 'OCCIDENTE' where code = '19318';
update cod_dane set courier = 'NORTE' where code = '13052';
update cod_dane set courier = 'NORTE' where code = '13580';
update cod_dane set courier = 'SUR' where code = '41615';
update cod_dane set courier = 'CENTRO B' where code = '15047';
update cod_dane set courier = 'CENTRO B' where code = '85279';
update cod_dane set courier = 'ORIENTE' where code = '20400';
update cod_dane set courier = 'NORTE' where code = '13188';
update cod_dane set courier = 'ORIENTE' where code = '68867';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05858';
update cod_dane set courier = 'EJE CAFETERO' where code = '17665';
update cod_dane set courier = 'ORIENTE' where code = '68081';
update cod_dane set courier = 'CENTRO B' where code = '95001';
update cod_dane set courier = 'NORTE' where code = '47660';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27660';
update cod_dane set courier = 'OCCIDENTE' where code = '52001';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27073';
update cod_dane set courier = 'CENTRO B' where code = '15180';
update cod_dane set courier = 'OCCIDENTE' where code = '76520';
update cod_dane set courier = 'CENTRO B' where code = '85125';
update cod_dane set courier = 'OCCIDENTE' where code = '52520';
update cod_dane set courier = 'NORTE' where code = '13620';
update cod_dane set courier = 'OCCIDENTE' where code = '52885';
update cod_dane set courier = 'ORIENTE' where code = '68861';
update cod_dane set courier = 'CENTRO B' where code = '15755';
update cod_dane set courier = 'OCCIDENTE' where code = '76377';
update cod_dane set courier = 'CENTRO B' where code = '15367';
update cod_dane set courier = 'ORIENTE' where code = '68573';
update cod_dane set courier = 'CENTRO B' where code = '25736';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05652';
update cod_dane set courier = 'CENTRO B' where code = '15763';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05425';
update cod_dane set courier = 'EJE CAFETERO' where code = '63594';
update cod_dane set courier = 'EJE CAFETERO' where code = '63212';
update cod_dane set courier = 'NORTE' where code = '47703';
update cod_dane set courier = 'CENTRO B' where code = '15332';
update cod_dane set courier = 'CENTRO B' where code = '85300';
update cod_dane set courier = 'ORIENTE' where code = '68500';
update cod_dane set courier = 'NORTE' where code = '13473';
update cod_dane set courier = 'OCCIDENTE' where code = '76828';
update cod_dane set courier = 'ORIENTE' where code = '54498';
update cod_dane set courier = 'NORTE' where code = '08606';
update cod_dane set courier = 'OCCIDENTE' where code = '52079';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05809';
update cod_dane set courier = 'ORIENTE' where code = '68418';
update cod_dane set courier = 'CENTRO B' where code = '15690';
update cod_dane set courier = 'CENTRO B' where code = '15325';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05854';
update cod_dane set courier = 'ORIENTE' where code = '68077';
update cod_dane set courier = 'SUR' where code = '73563';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27615';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05697';
update cod_dane set courier = 'SUR' where code = '73124';
update cod_dane set courier = 'SUR' where code = '41885';
update cod_dane set courier = 'EJE CAFETERO' where code = '17446';
update cod_dane set courier = 'ORIENTE' where code = '54250';
update cod_dane set courier = 'OCCIDENTE' where code = '52788';
update cod_dane set courier = 'NORTE' where code = '47460';
update cod_dane set courier = 'CENTRO B' where code = '25823';
update cod_dane set courier = 'EJE CAFETERO' where code = '17777';
update cod_dane set courier = 'CENTRO B' where code = '15407';
update cod_dane set courier = 'OCCIDENTE' where code = '52693';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05656';
update cod_dane set courier = 'ORIENTE' where code = '81300';
update cod_dane set courier = 'CENTRO B' where code = '25095';
update cod_dane set courier = 'SUR' where code = '41244';
update cod_dane set courier = 'EJE CAFETERO' where code = '17513';
update cod_dane set courier = 'OCCIDENTE' where code = '52083';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05059';
update cod_dane set courier = 'NORTE' where code = '23686';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05190';
update cod_dane set courier = 'NORTE' where code = '70823';
update cod_dane set courier = 'CENTRO B' where code = '25488';
update cod_dane set courier = 'CENTRO B' where code = '85250';
update cod_dane set courier = 'NORTE' where code = '13873';
update cod_dane set courier = 'ORIENTE' where code = '68013';
update cod_dane set courier = 'CENTRO B' where code = '25368';
update cod_dane set courier = 'OCCIDENTE' where code = '76890';
update cod_dane set courier = 'CENTRO B' where code = '15798';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05736';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05318';
update cod_dane set courier = 'CENTRO B' where code = '50689';
update cod_dane set courier = 'CENTRO B' where code = '25288';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05147';
update cod_dane set courier = 'OCCIDENTE' where code = '76895';
update cod_dane set courier = 'NORTE' where code = '13074';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05088';
update cod_dane set courier = 'EJE CAFETERO' where code = '63001';
update cod_dane set courier = 'ORIENTE' where code = '68684';
update cod_dane set courier = 'OCCIDENTE' where code = '52385';
update cod_dane set courier = 'CENTRO B' where code = '25260';
update cod_dane set courier = 'NORTE' where code = '23815';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05856';
update cod_dane set courier = 'NORTE' where code = '23682';
update cod_dane set courier = 'ORIENTE' where code = '68169';
update cod_dane set courier = 'CENTRO B' where code = '95025';
update cod_dane set courier = 'OCCIDENTE' where code = '52203';
update cod_dane set courier = 'CENTRO B' where code = '25335';
update cod_dane set courier = 'ORIENTE' where code = '68160';
update cod_dane set courier = 'NORTE' where code = '13650';
update cod_dane set courier = 'CENTRO B' where code = '15090';
update cod_dane set courier = 'EJE CAFETERO' where code = '17042';
update cod_dane set courier = 'CENTRO B' where code = '25805';
update cod_dane set courier = 'NORTE' where code = '13673';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05847';
update cod_dane set courier = 'OCCIDENTE' where code = '52573';
update cod_dane set courier = 'CENTRO B' where code = '15204';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05038';
update cod_dane set courier = 'OCCIDENTE' where code = '19573';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05306';
update cod_dane set courier = 'SUR' where code = '18756';
update cod_dane set courier = 'SUR' where code = '41078';
update cod_dane set courier = 'CENTRO B' where code = '50370';
update cod_dane set courier = 'SUR' where code = '73268';
update cod_dane set courier = 'CENTRO B' where code = '25258';
update cod_dane set courier = 'SUR' where code = '73347';
update cod_dane set courier = 'CENTRO B' where code = '25743';
update cod_dane set courier = 'NORTE' where code = '70702';
update cod_dane set courier = 'CENTRO B' where code = '25214';
update cod_dane set courier = 'NORTE' where code = '70265';
update cod_dane set courier = 'ORIENTE' where code = '68820';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05579';
update cod_dane set courier = 'NORTE' where code = '23555';
update cod_dane set courier = 'CENTRO B' where code = '15162';
update cod_dane set courier = 'CENTRO B' where code = '85162';
update cod_dane set courier = 'SUR' where code = '73270';
update cod_dane set courier = 'ORIENTE' where code = '68468';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05206';
update cod_dane set courier = 'CENTRO B' where code = '25871';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05284';
update cod_dane set courier = 'CENTRO B' where code = '15401';
update cod_dane set courier = 'ORIENTE' where code = '54223';
update cod_dane set courier = 'NORTE' where code = '44378';
update cod_dane set courier = 'CENTRO B' where code = '91540';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05154';
update cod_dane set courier = 'NORTE' where code = '70204';
update cod_dane set courier = 'CENTRO B' where code = '50001';
update cod_dane set courier = 'CENTRO B' where code = '15317';
update cod_dane set courier = 'CENTRO B' where code = '15135';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27787';
update cod_dane set courier = 'CENTRO B' where code = '25653';
update cod_dane set courier = 'ORIENTE' where code = '68406';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05576';
update cod_dane set courier = 'CENTRO B' where code = '25740';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05873';
update cod_dane set courier = 'ORIENTE' where code = '20614';
update cod_dane set courier = 'ORIENTE' where code = '54480';
update cod_dane set courier = 'OCCIDENTE' where code = '19300';
update cod_dane set courier = 'CENTRO B' where code = '25040';
update cod_dane set courier = 'CENTRO B' where code = '15494';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05040';
update cod_dane set courier = 'CENTRO B' where code = '15580';
update cod_dane set courier = 'CENTRO B' where code = '15238';
update cod_dane set courier = 'CENTRO B' where code = '15218';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05649';
update cod_dane set courier = 'ORIENTE' where code = '68296';
update cod_dane set courier = 'SUR' where code = '18460';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05237';
update cod_dane set courier = 'CENTRO B' where code = '15822';
update cod_dane set courier = 'ORIENTE' where code = '54344';
update cod_dane set courier = 'EJE CAFETERO' where code = '17174';
update cod_dane set courier = 'EJE CAFETERO' where code = '17442';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05615';
update cod_dane set courier = 'CENTRO B' where code = '25645';
update cod_dane set courier = 'OCCIDENTE' where code = '19845';
update cod_dane set courier = 'OCCIDENTE' where code = '76001';
update cod_dane set courier = 'SUR' where code = '73026';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05480';
update cod_dane set courier = 'ORIENTE' where code = '68320';
update cod_dane set courier = 'ORIENTE' where code = '68327';
update cod_dane set courier = 'NORTE' where code = '44098';
update cod_dane set courier = 'CENTRO B' where code = '15720';
update cod_dane set courier = 'NORTE' where code = '13433';
update cod_dane set courier = 'SUR' where code = '41518';
update cod_dane set courier = 'ORIENTE' where code = '20228';
update cod_dane set courier = 'OCCIDENTE' where code = '52323';
update cod_dane set courier = 'SUR' where code = '18029';
update cod_dane set courier = 'OCCIDENTE' where code = '19513';
update cod_dane set courier = 'CENTRO B' where code = '15114';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05138';
update cod_dane set courier = 'NORTE' where code = '08573';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05212';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05585';
update cod_dane set courier = 'CENTRO B' where code = '25438';
update cod_dane set courier = 'OCCIDENTE' where code = '52720';
update cod_dane set courier = 'NORTE' where code = '13006';
update cod_dane set courier = 'CENTRO B' where code = '15236';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05887';
update cod_dane set courier = 'SUR' where code = '41503';
update cod_dane set courier = 'CENTRO B' where code = '15599';
update cod_dane set courier = 'NORTE' where code = '13657';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05690';
update cod_dane set courier = 'CENTRO B' where code = '15109';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27425';
update cod_dane set courier = 'OCCIDENTE' where code = '52540';
update cod_dane set courier = 'SUR' where code = '73870';
update cod_dane set courier = 'CENTRO B' where code = '25426';
update cod_dane set courier = 'CENTRO B' where code = '15757';
update cod_dane set courier = 'CENTRO B' where code = '25175';
update cod_dane set courier = 'SUR' where code = '73283';
update cod_dane set courier = 'ORIENTE' where code = '81591';
update cod_dane set courier = 'NORTE' where code = '44855';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05091';
update cod_dane set courier = 'SUR' where code = '73854';
update cod_dane set courier = 'CENTRO B' where code = '50400';
update cod_dane set courier = 'CENTRO B' where code = '25473';
update cod_dane set courier = 'ORIENTE' where code = '54109';
update cod_dane set courier = 'NORTE' where code = '47189';
update cod_dane set courier = 'OCCIDENTE' where code = '52250';
update cod_dane set courier = 'OCCIDENTE' where code = '52835';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05353';
update cod_dane set courier = 'ORIENTE' where code = '54206';
update cod_dane set courier = 'CENTRO B' where code = '25183';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05659';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05051';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05044';
update cod_dane set courier = 'CENTRO B' where code = '15837';
update cod_dane set courier = 'ORIENTE' where code = '68682';
update cod_dane set courier = 'SUR' where code = '41551';
update cod_dane set courier = 'NORTE' where code = '23672';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05604';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05490';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27077';
update cod_dane set courier = 'ORIENTE' where code = '20013';
update cod_dane set courier = 'CENTRO B' where code = '15516';
update cod_dane set courier = 'CENTRO B' where code = '97161';
update cod_dane set courier = 'NORTE' where code = '70001';
update cod_dane set courier = 'CENTRO B' where code = '15740';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27099';
update cod_dane set courier = 'CENTRO B' where code = '15759';
update cod_dane set courier = 'SUR' where code = '41770';
update cod_dane set courier = 'ORIENTE' where code = '54172';
update cod_dane set courier = 'CENTRO B' where code = '15762';
update cod_dane set courier = 'CENTRO B' where code = '25099';
update cod_dane set courier = 'ORIENTE' where code = '68266';
update cod_dane set courier = 'SUR' where code = '41020';
update cod_dane set courier = 'CENTRO B' where code = '25126';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05321';
update cod_dane set courier = 'SUR' where code = '41530';
update cod_dane set courier = 'ORIENTE' where code = '20011';
update cod_dane set courier = 'CENTRO B' where code = '15632';
update cod_dane set courier = 'SUR' where code = '73236';
update cod_dane set courier = 'CENTRO B' where code = '15212';
update cod_dane set courier = 'OCCIDENTE' where code = '19824';
update cod_dane set courier = 'ORIENTE' where code = '68217';
update cod_dane set courier = 'OCCIDENTE' where code = '76318';
update cod_dane set courier = 'NORTE' where code = '23675';
update cod_dane set courier = 'ORIENTE' where code = '54418';
update cod_dane set courier = 'CENTRO B' where code = '15272';
update cod_dane set courier = 'NORTE' where code = '08634';
update cod_dane set courier = 'SUR' where code = '73547';
update cod_dane set courier = 'ORIENTE' where code = '68167';
update cod_dane set courier = 'SUR' where code = '41006';
update cod_dane set courier = 'SUR' where code = '41483';
update cod_dane set courier = 'ORIENTE' where code = '68547';
update cod_dane set courier = 'OCCIDENTE' where code = '19142';
update cod_dane set courier = 'SUR' where code = '73861';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27361';
update cod_dane set courier = 'ORIENTE' where code = '68377';
update cod_dane set courier = 'ORIENTE' where code = '54680';
update cod_dane set courier = 'EJE CAFETERO' where code = '63190';
update cod_dane set courier = 'CENTRO B' where code = '15377';
update cod_dane set courier = 'CENTRO B' where code = '91530';
update cod_dane set courier = 'SUR' where code = '73217';
update cod_dane set courier = 'OCCIDENTE' where code = '19585';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05543';
update cod_dane set courier = 'OCCIDENTE' where code = '76111';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05055';
update cod_dane set courier = 'EJE CAFETERO' where code = '66687';
update cod_dane set courier = 'CENTRO B' where code = '94343';
update cod_dane set courier = 'OCCIDENTE' where code = '19809';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27372';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27050';
update cod_dane set courier = 'CENTRO B' where code = '25293';
update cod_dane set courier = 'NORTE' where code = '44847';
update cod_dane set courier = 'SUR' where code = '41801';
update cod_dane set courier = 'ORIENTE' where code = '68780';
update cod_dane set courier = 'CENTRO B' where code = '25785';
update cod_dane set courier = 'SUR' where code = '73352';
update cod_dane set courier = 'NORTE' where code = '13549';
update cod_dane set courier = 'NORTE' where code = '44078';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05282';
update cod_dane set courier = 'OCCIDENTE' where code = '76616';
update cod_dane set courier = 'OCCIDENTE' where code = '76122';
update cod_dane set courier = 'NORTE' where code = '23574';
update cod_dane set courier = 'OCCIDENTE' where code = '19622';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05842';
update cod_dane set courier = 'CENTRO B' where code = '94888';
update cod_dane set courier = 'OCCIDENTE' where code = '76113';
update cod_dane set courier = 'OCCIDENTE' where code = '52687';
update cod_dane set courier = 'ORIENTE' where code = '68872';
update cod_dane set courier = 'CENTRO B' where code = '25407';
update cod_dane set courier = 'ORIENTE' where code = '68101';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05501';
update cod_dane set courier = 'CENTRO B' where code = '85010';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27245';
update cod_dane set courier = 'CENTRO B' where code = '25612';
update cod_dane set courier = 'CENTRO B' where code = '15185';
update cod_dane set courier = 'NORTE' where code = '44110';
update cod_dane set courier = 'NORTE' where code = '70215';
update cod_dane set courier = 'EJE CAFETERO' where code = '66572';
update cod_dane set courier = 'CENTRO B' where code = '15466';
update cod_dane set courier = 'CENTRO B' where code = '94885';
update cod_dane set courier = 'NORTE' where code = '47058';
update cod_dane set courier = 'NORTE' where code = '70708';
update cod_dane set courier = 'SUR' where code = '41026';
update cod_dane set courier = 'EJE CAFETERO' where code = '17614';
update cod_dane set courier = 'NORTE' where code = '47541';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05310';
update cod_dane set courier = 'CENTRO B' where code = '91430';
update cod_dane set courier = 'OCCIDENTE' where code = '52233';
update cod_dane set courier = 'ORIENTE' where code = '68895';
update cod_dane set courier = 'NORTE' where code = '44874';
update cod_dane set courier = 'ORIENTE' where code = '68209';
update cod_dane set courier = 'SUR' where code = '18205';
update cod_dane set courier = 'CENTRO B' where code = '25486';
update cod_dane set courier = 'CENTRO B' where code = '25168';
update cod_dane set courier = 'CENTRO B' where code = '97666';
update cod_dane set courier = 'CENTRO B' where code = '94663';
update cod_dane set courier = 'SUR' where code = '73678';
update cod_dane set courier = 'SUR' where code = '73624';
update cod_dane set courier = 'SUR' where code = '73675';
update cod_dane set courier = 'CENTRO B' where code = '15621';
update cod_dane set courier = 'NORTE' where code = '13468';
update cod_dane set courier = 'EJE CAFETERO' where code = '66318';
update cod_dane set courier = 'CENTRO B' where code = '25815';
update cod_dane set courier = 'CENTRO B' where code = '25339';
update cod_dane set courier = 'CENTRO B' where code = '25845';
update cod_dane set courier = 'CENTRO B' where code = '25580';
update cod_dane set courier = 'NORTE' where code = '23580';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05360';
update cod_dane set courier = 'CENTRO B' where code = '25599';
update cod_dane set courier = 'ORIENTE' where code = '54347';
update cod_dane set courier = 'NORTE' where code = '13300';
update cod_dane set courier = 'SUR' where code = '18753';
update cod_dane set courier = 'CENTRO B' where code = '99773';
update cod_dane set courier = 'CENTRO B' where code = '25535';
update cod_dane set courier = 'CENTRO B' where code = '25506';
update cod_dane set courier = 'ORIENTE' where code = '68655';
update cod_dane set courier = 'OCCIDENTE' where code = '19256';
update cod_dane set courier = 'NORTE' where code = '08832';
update cod_dane set courier = 'NORTE' where code = '47570';
update cod_dane set courier = 'OCCIDENTE' where code = '52356';
update cod_dane set courier = 'EJE CAFETERO' where code = '66400';
update cod_dane set courier = 'ORIENTE' where code = '68689';
update cod_dane set courier = 'CENTRO B' where code = '25402';
update cod_dane set courier = 'NORTE' where code = '70110';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05647';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05368';
update cod_dane set courier = 'ORIENTE' where code = '20178';
update cod_dane set courier = 'OCCIDENTE' where code = '76834';
update cod_dane set courier = 'NORTE' where code = '23855';
update cod_dane set courier = 'OCCIDENTE' where code = '19290';
update cod_dane set courier = 'OCCIDENTE' where code = '19392';
update cod_dane set courier = 'CENTRO B' where code = '15572';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05658';
update cod_dane set courier = 'NORTE' where code = '23464';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05042';
update cod_dane set courier = 'ORIENTE' where code = '68298';
update cod_dane set courier = 'NORTE' where code = '23670';
update cod_dane set courier = 'ORIENTE' where code = '68235';
update cod_dane set courier = 'CENTRO B' where code = '25086';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05125';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '27205';
update cod_dane set courier = 'OCCIDENTE' where code = '52110';
update cod_dane set courier = 'OCCIDENTE' where code = '52352';
update cod_dane set courier = 'CENTRO B' where code = '99624';
update cod_dane set courier = 'SUR' where code = '18094';
update cod_dane set courier = 'OCCIDENTE' where code = '52405';
update cod_dane set courier = 'CENTRO B' where code = '50318';
update cod_dane set courier = 'ORIENTE' where code = '20250';
update cod_dane set courier = 'CENTRO B' where code = '15187';
update cod_dane set courier = 'ORIENTE' where code = '68705';
update cod_dane set courier = 'CENTRO B' where code = '25328';
update cod_dane set courier = 'NORTE' where code = '23079';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05475';
update cod_dane set courier = 'CENTRO B' where code = '15835';
update cod_dane set courier = 'CENTRO B' where code = '15224';
update cod_dane set courier = 'SUR' where code = '73226';
update cod_dane set courier = 'EJE CAFETERO' where code = '17867';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05895';
update cod_dane set courier = 'ORIENTE' where code = '68147';
update cod_dane set courier = 'CENTRO B' where code = '25297';
update cod_dane set courier = 'OCCIDENTE' where code = '76869';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05674';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05313';
update cod_dane set courier = 'CENTRO B' where code = '91669';
update cod_dane set courier = 'ORIENTE' where code = '68679';
update cod_dane set courier = 'CENTRO B' where code = '25873';
update cod_dane set courier = 'NORTE' where code = '08685';
update cod_dane set courier = 'NORTE' where code = '23466';
update cod_dane set courier = 'CENTRO B' where code = '15660';
update cod_dane set courier = 'NORTE' where code = '13654';
update cod_dane set courier = 'NORTE' where code = '70820';
update cod_dane set courier = 'CENTRO B' where code = '50590';
update cod_dane set courier = 'CENTRO B' where code = '25875';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05756';
update cod_dane set courier = 'ORIENTE' where code = '54385';
update cod_dane set courier = 'OCCIDENTE' where code = '52036';
update cod_dane set courier = 'CENTRO B' where code = '50680';
update cod_dane set courier = 'SUR' where code = '73168';
update cod_dane set courier = 'CENTRO B' where code = '25491';
update cod_dane set courier = 'SUR' where code = '73770';
update cod_dane set courier = 'NORTE' where code = '13490';
update cod_dane set courier = 'OCCIDENTE' where code = '19212';
update cod_dane set courier = 'CENTRO B' where code = '15842';
update cod_dane set courier = 'NORTE' where code = '70523';
update cod_dane set courier = 'OCCIDENTE' where code = '52258';
update cod_dane set courier = 'OCCIDENTE' where code = '52565';
update cod_dane set courier = 'CENTRO B' where code = '15879';
update cod_dane set courier = 'OCCIDENTE' where code = '52210';
update cod_dane set courier = 'NORTE' where code = '47205';
update cod_dane set courier = 'CENTRO B' where code = '85410';
update cod_dane set courier = 'EJE CAFETERO' where code = '66075';
update cod_dane set courier = 'CENTRO B' where code = '15537';
update cod_dane set courier = 'ORIENTE' where code = '68176';
update cod_dane set courier = 'SUR' where code = '41013';
update cod_dane set courier = 'NORTE' where code = '13062';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05266';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05101';
update cod_dane set courier = 'CENTRO B' where code = '25436';
update cod_dane set courier = 'OCCIDENTE' where code = '76400';
update cod_dane set courier = 'OCCIDENTE' where code = '52051';
update cod_dane set courier = 'CENTRO B' where code = '25777';
update cod_dane set courier = 'NOR-OCCIDENTE' where code = '05890';
update cod_dane set courier = 'CENTRO B' where code = '15600';
update cod_dane set courier = 'OCCIDENTE' where code = '76248';
update cod_dane set courier = 'OCCIDENTE' where code = '52399';
update cod_dane set courier = 'OCCIDENTE' where code = '76563';
update cod_dane set courier = 'ORIENTE' where code = '20045';
