courier_service:
    path: /wscolpensionesPROD/ServiceColpensiones
    controller: App\DocumentManagement\Application\Controller\SaveInformationController
    defaults: { auth: false }
    methods: [ GET, POST ]


# Routes Front
login:
    path: /login
    controller: App\FrontApp\Application\Controller\LoginController::login
admin:
    path: /admin
    controller: App\FrontApp\Application\Controller\AdminController::admin
home:
    path: /
    controller: App\FrontApp\Application\Controller\HomeController::index