courier_service:
    path: /wscolpensionesQA/ServiceColpensiones
    controller: App\DocumentManagement\Application\Controller\SaveInformationController
    defaults: { auth: false }
    methods: [ GET, POST ]
