courier_service:
    path: /wscolpensionesPROD/ServiceColpensiones
    controller: App\DocumentManagement\Application\Controller\SaveInformationController
    defaults: { auth: false }
    methods: [ GET, POST ]


# Routes Front
login:
    path: /login
    controller: App\FrontApp\Application\Controller\LoginController::login
admin:
    path: /admin
    controller: App\FrontApp\Application\Controller\AdminController::admin
home:
    path: /
    controller: App\FrontApp\Application\Controller\HomeController::index
filed:
    path: /filed
    controller: App\FrontApp\Application\Controller\FiledController::index
documents:
    path: /documents
    controller: App\FrontApp\Application\Controller\DocumentController::index
logs:
    path: /logs
    controller: App\FrontApp\Application\Controller\LogController::index
logs-documents:
    path: /logs-documents
    controller: App\FrontApp\Application\Controller\LogDocumentController::index